[package]
name = "file_search"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "search"
path = "src/search.rs"


#[[bin]]
#name = "setup"
#path = "src/setup.rs"

[dependencies]
rusqlite = "0.28"
walkdir = "2.5.0"
